spring:
  application:
    name: gateway-service


mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
server:
  port: 8091
feign:
  circuitbreaker:
    enabled=true:
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8760}/eureka/
    healthcheck:
      enabled: true # for Actuator
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    path: /swagger-ui
